### ISSUE TITLE
help, I got error msg

### ISSUE THREAD

**Issue by Carla-33** [graw1988/ns3.30.1_BlackHoleAttack#2]
Hi
I got this error, could you please help?

msg="Invalid attribute set (RxSensitivity) on ns3::YansWifiPhy", file=../src/core/model/object-factory.cc, line=53
terminate called without an active exception

thank

**Comment by timetravel-Err** [comment]
Hi, 
Reading the error message  "Invalid attribute set (RxSensitivity) on ns3::YansWifiPhy" 

It seems, something is wrong with the attributes in YansWifiPhy.

Please check my code for reference. 

(you can share your code section and NS3 version)

**Comment by Carla-33** [comment]
HI;
I have tried to use your own code, but this message still appears.

like that:
'build' finished successfully (1.469s)
msg="Invalid attribute set (RxSensitivity) on ns3::YansWifiPhy", file=../src/core/model/object-factory.cc, line=53
terminate called without an active exception
Command ['/home/user/Desktop/ns-allinone-3.27/ns-3.27/build/scratch/blackhole'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

my version is ns-allinone-3.27

Thank

**Comment by timetravel-Err** [comment]
Hi,

if you follow https://www.nsnam.org/docs/release/3.27/doxygen/_attribute_list.html 
and look for "ns3::WifiPhy", the attribute "RxSensitivity" is not listed under it. 
Hence you are getting the error message when using the code on ns3.27.

I used ns3.30.1 , check this https://www.nsnam.org/docs/release/3.30/doxygen/_attribute_list.html 
You will find "RxSensitivity" under "ns3::WifiPhy".

You may use "EnergyDetectionThreshold" for your ns3.27.

Doxygen is a good place to start exploring attributes and stuff... and ns3 versions do bring changes (look for changes link under any particular ns3 release).

Hope this helps.
