### ISSUE TITLE
explain the aodv

### ISSUE THREAD

**Issue by Carla-33** [graw1988/ns3.30.1_BlackHoleAttack#3]
Hi,

Could you please explain more the different between these two file:

(a) aodv-routing-protocol_basic.cc for every packet drop behavior

(b) aodv-routing-protocol_advance.cc for alternate packet drop behavior
 
Another question: Do you have a code for Wormhole attack?

Thank you

**Comment by timetravel-Err** [comment]
(a)A malicious node utilizes the aodv routing protocol to claim itself of being the shortest path to the destination node, but drops the routing packets (does not forward packets to its neighbors).

(b)A malicious node utilizes the aodv routing protocol to claim itself of being the shortest path to the destination node, but changes its behaviour( switches between forward and drop).

Do you have a code for Wormhole attack?
-No
